const languages = {
  af: "afrikaans",
  ga: "irish",
  sq: "albanian",
  it: "italian",
  ar: "arabic",
  ja: "japanese",
  az: "azerbaijani",
  kn: "kannada",
  eu: "basque",
  ko: "korean",
  bn: "bengali",
  la: "latin",
  be: "belarusian",
  lv: "latvian",
  bg: "bulgarian",
  lt: "lithuanian",
  ca: "catalan",
  mk: "macedonian",
  "zh-CN": "chinese simplified",
  ms: "malay",
  "zh-TW": "chinese traditional",
  mt: "maltese",
  hr: "croatian",
  no: "norwegian",
  cs: "czech",
  fa: "persian",
  da: "danish",
  pl: "polish",
  nl: "dutch",
  pt: "portuguese",
  en: "english",
  ro: "romanian",
  eo: "esperanto",
  ru: "russian",
  et: "estonian",
  sr: "serbian",
  tl: "filipino",
  sk: "slovak",
  fi: "finnish",
  sl: "slovenian",
  fr: "french",
  es: "spanish",
  gl: "galician",
  sw: "swahili",
  ka: "georgian",
  sv: "swedish",
  de: "german",
  ta: "tamil",
  el: "greek",
  te: "telugu",
  gu: "gujarati",
  th: "thai",
  ht: "haitian creole",
  tr: "turkish",
  iw: "hebrew",
  uk: "ukrainian",
  hi: "hindi",
  ur: "urdu",
  hu: "hungarian",
  vi: "vietnamese",
  is: "icelandic",
  cy: "welsh",
  id: "indonesian",
  yi: "yiddish",
};

export default languages;
