name: Build and Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  BACKEND_IMAGE: ghcr.io/${{ github.repository }}-backend:latest

jobs:
  build-and-publish-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: ${{ env.BACKEND_IMAGE }}
          build-args: |
            GENIUS_SECRET=${{ secrets.GENIUS_SECRET }}

  deploy-backend:
    needs: build-and-publish-backend
    runs-on: ubuntu-latest

    steps:
      - name: SSH to the server and deploy backend Docker container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull ${{ env.BACKEND_IMAGE }}
            docker stop backend || true
            docker rm backend || true
            docker run -d --name backend -p 3000:3000 ${{ env.BACKEND_IMAGE }}
