name: Build and Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  FRONTEND_IMAGE: ghcr.io/${{ github.repository }}-frontend:latest

jobs:
  build-and-publish-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          tags: ${{ env.FRONTEND_IMAGE }}
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}

  deploy-frontend:
    needs: build-and-publish-frontend
    runs-on: ubuntu-latest

    steps:
      - name: SSH to the server and deploy frontend Docker container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull ${{ env.FRONTEND_IMAGE }}
            docker stop frontend || true
            docker rm frontend || true
            docker run -d --name frontend -p 8000:3000 ${{ env.FRONTEND_IMAGE }}
